name: Test services

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        svc:
          [
            "api-gateway",
            "auth-svc",
            "meal-svc",
            "common",
            "diary-client"
          ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: magnetikonline/action-golang-cache@v4
        with:
          go-version: "^1.19"
          cache-key-suffix: ${{matrix.svc}}
      - name: Install protoc
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: protobuf-compiler
          version: latest
      - name: Install go proto plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
          export PATH="$PATH:$(go env GOPATH)/bin"
      - name: Create proto files
        run: cd common && make proto && cd ..
      - name: Test
        run: cd ${{matrix.svc}} && make test
