name: Test services

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    strategy:
      matrix:
        svc: [ "api-gateway", "auth-svc", "meal-svc", "diary-client" ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: pushd ${{matrix.svc}} && make test
