name: Test services

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        svc:
          [
            "api-gateway",
            "auth-svc",
            "meal-svc",
            "diary-client",
            "common"
          ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: cd ${{matrix.svc}} && make test
